In [ ]:
%matplotlib inline

# PyTorch

PyTorch es un **Framework de Deep Learning** de código abierto que se utiliza para desarrollar y entrenar redes neuronales. Es desarrollado principalmente por el grupo de investigación de IA de Facebook. PyTorch se puede usar tanto con Python como con C++. Naturalmente, la interfaz de Python está más pulida. 

Un Framework de Deep Learning es un conjunto de interfaces, librerías o herramientas que nos permiten construir modelos de aprendizaje profundo de manera más fácil y rápida, sin entrar en los detalles de los algoritmos subyacentes. Proporcionan una forma clara y concisa de definir modelos utilizando una colección de componentes optimizados y prediseñados. Sus principales características son:
* Codificación en alto nivel
* Cálculo automático de los gradientes
* Paralelización de los procesos
* Soporte de la comunidad

A diferencia de la mayoría de los otros frameworks populares como TensorFlow, que utilizan grafos computacionales estáticos, PyTorch utiliza grafos dinámicos, lo que permite una mayor flexibilidad en la construcción de arquitecturas complejas. 

Además, Pytorch utiliza conceptos básicos de Python como clases, estructuras y bucles condicionales, que son muy familiares para nuestros ojos y, por lo tanto, mucho más intuitivos de entender. Esto lo hace mucho más simple que otros frameworks como TensorFlow que aportan su propio estilo de programación.




Introducción a los Tensores de PyTorch
===============================

Los tensores son la abstracción de datos central en PyTorch. Este notebook interactivo
 proporciona una introducción detallada a la clase ``torch.Tensor``.

Lo primero es lo primero, importemos el módulo PyTorch. También agregaremos
el módulo `math` de Python para facilitar algunos de los ejemplos.


In [3]:
import torch
import math

Crear tensores
----------------

La forma más sencilla de crear un tensor es con la llamada ``torch.empty()``:




In [ ]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[3.5174e-35, 0.0000e+00, 3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22]])


Desempaquemos lo que acabamos de hacer:

- Creamos un tensor utilizando uno de los numerosos métodos constructores provistos por ``torch``.
- El tensor en sí es bidimensional, tiene 3 filas y 4 columnas.
- El tipo de objeto devuelto es ``torch.Tensor``, que es un
   alias para ``torch.FloatTensor``; por defecto, los tensores de PyTorch son
   poblados con números de punto flotante de 32 bits. 
- Probablemente verá algunos valores de aspecto aleatorio al imprimir su
   tensor. La llamada ``torch.empty()`` asigna memoria para el tensor,
   pero no lo inicializa con ningún valor, por lo que lo que está viendo es
   lo que estaba en la memoria en el momento de la asignación.

Una breve nota sobre los tensores y su número de dimensiones, y
terminología:

- A veces verás un tensor unidimensional llamado
   **vector**
- Del mismo modo, un tensor bidimensional a menudo se denomina
   **matriz**
- Cualquier cosa con más de dos dimensiones generalmente es solo
   llamado tensor.

La mayoría de las veces, querrá inicializar su tensor con algún
valor. Los casos comunes son todos ceros, todos unos o valores aleatorios, y el
El módulo ``torch`` proporciona métodos constructores para todos estos:




In [ ]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


Todos los métodos constructores hacen exactamente lo que cabría esperar: tenemos un tensor
llena de ceros, otro llena de unos y otro con valores aleatorios
entre 0 y 1.

### Tensores Aleatorios y Semillas

Hablando del tensor aleatorio, ¿notaste la llamada a
``torch.manual_seed()`` inmediatamente anterior? Inicializar tensores,
como los pesos de aprendizaje de un modelo, con valores aleatorios es común pero
hay momentos, especialmente en entornos de investigación, en los que querrá
cierta seguridad de la reproducibilidad de sus resultados. Asignar manualmente 
la semilla de su generador de números aleatorios es la forma de hacer esto. Miremos
más cerca:




In [ ]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


Lo que deberías ver arriba es que ``random1`` y ``random3`` llevan
valores idénticos, al igual que ``random2`` y ``random4``. La asignación manual
la semilla del generador de numeros aleatorios lo reinicia, de modo que los cálculos idénticos 
números aleatorios deberían, en la mayoría de los entornos, proporcionar resultados idénticos.

Para obtener más información, consulte la documentación de PyTorch sobre
reproducibilidad <https://pytorch.org/docs/stable/notes/randomness.html>`__.






### Formas de los Tensores

A menudo, para poder realizar operaciones en dos o más tensores, estos
tendrán que tener la misma ***forma***, es decir, tener el mismo número de
dimensiones y el mismo número de celdas en cada dimensión. Para garantizar eso existen los métodos ``torch.*_like()``:

In [ ]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[3.5176e-35, 0.0000e+00, 1.5695e-43],
         [1.6255e-43, 1.6956e-43, 1.3312e-43]],

        [[1.5134e-43, 1.4714e-43, 1.4994e-43],
         [1.4153e-43, 1.3312e-43, 1.6816e-43]]])
torch.Size([2, 2, 3])
tensor([[[3.5176e-35, 0.0000e+00, 3.3631e-44],
         [0.0000e+00,        nan, 1.5912e+00]],

        [[1.1578e+27, 1.1362e+30, 7.1547e+22],
         [4.5828e+30, 1.2121e+04, 7.1846e+22]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


Lo primero nuevo en la celda de código de arriba es el uso del atributo ``.shape``
de todo tensor. Este atributo contiene una lista con el tamaño de
cada dimensión de un tensor - en nuestro caso, ``x`` es un tensor tridimensional
 con forma 2 x 2 x 3.

Debajo de eso, llamamos a los métodos ``.empty_like()``, ``.zeros_like()``,
``.ones_like()`` y ``.rand_like()``. Usando el atributo ``.shape``, podemos verificar que cada uno de estos métodos devuelve un tensor de
dimensionalidad y extensión idénticas.

La última forma de crear un tensor es especificar sus datos
directamente desde una colección de PyTorch:



In [ ]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


Usar ``torch.tensor()`` es la forma más sencilla de crear un
tensor si ya tiene datos en una tupla o lista de Python. Como se muestra
anterior, el anidamiento de las colecciones dará como resultado un tensor multidimensional.


### Tipos de datos de un Tensor

Establecer el tipo de datos de un tensor es posible de dos maneras:



In [ ]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


La forma más sencilla de establecer el tipo de datos subyacente de un tensor es con un
argumento opcional en el momento de la creación. En la primera línea de la celda de arriba,
configuramos ``dtype=torch.int16`` para el tensor ``a``. Cuando imprimimos ``a``,
podemos ver que está lleno de ``1`` en lugar de ``1.`` - La sutileza de Python
indica que este es un tipo entero en lugar de un punto flotante.

Otra cosa a tener en cuenta sobre la impresión de ``a`` es que, a diferencia de cuando
dejó ``dtype`` como predeterminado (coma flotante de 32 bits), imprimiendo el
tensor también especifica su ``dtype``.

Es posible que también haya notado que pasamos de especificar la forma del tensor como una serie de argumentos enteros, a agrupar esos argumentos en un
tupla. Esto no es estrictamente necesario: PyTorch tomará una serie de
argumentos enteros iniciales sin etiquetar como la forma del tensor, pero al agregar
los argumentos opcionales, ponerlos como tupla puede hacer que su intención sea más legible.

La otra forma de establecer el tipo de datos es con el método ``.to()``. En la
celda de arriba, creamos un tensor de punto flotante aleatorio ``b`` de la manera habitual. A continuación, creamos ``c`` convirtiendo ``b`` en un tensor entero  de 32 bits
con el método ``.to()``. Tenga en cuenta que ``c`` contiene todos los mismos
valores como ``b``, pero truncados a enteros.

Los tipos de datos disponibles incluyen:

-  ``torch.bool``
-  ``torch.int8``
-  ``torch.uint8``
-  ``torch.int16``
-  ``torch.int32``
-  ``torch.int64``
-  ``torch.half``
-  ``torch.float``
-  ``torch.double``
-  ``torch.bfloat``

Matemáticas y lógica con tensores PyTorch
---------------------------------

Ahora que conoces algunas de las formas de crear un tensor… ¿qué puedes hacer con ellos?

Veamos primero la aritmética básica y cómo interactúan los tensores con
escalares simples:




In [ ]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])



Como puedes ver arriba, las operaciones aritméticas entre tensores y escalares,
como suma, resta, multiplicación, división y
exponenciación se aplican elemento a elemento dentro del tensor. Dado que
la salida de tal operación será un tensor, puedes encadenarlos
junto con las reglas usuales de precedencia de operadores, como en la línea donde
creamos ``threes``.

Las operaciones similares entre dos tensores también se comportan intuitivamente:



In [ ]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


Es importante notar aquí que todos los tensores en la celda de código anterior
 eran de forma idéntica. ¿Qué sucede cuando tratamos de realizar una operación binaria entre tensores si la forma es diferente?

<div class="alert alert-info"><h4>Nota</h4><p>La siguiente celda arroja un error de tiempo de ejecución. Esto es intencional.</p></div>

In [ ]:
   a = torch.rand(2, 3)
   b = torch.rand(3, 2)

   print(a * b)

RuntimeError: ignored

### Broadcasting de Tensores

En el caso general, no se puede operar con tensores de diferente forma
de esta manera, incluso en un caso como el de la celda anterior, donde los tensores tienen un
idéntico número de elementos.

<div class="alert alert-info"><h4>Nota</h4><p>Si está familiarizado con el broadcasting de NumPy, aquí se aplican las mismas reglas.</p></div>

La excepción a la regla de las mismas formas es el ***broadcasting de tensores***. Aquí hay
un ejemplo:




In [ ]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.2024, 0.5731, 0.7191, 0.4067],
        [0.7301, 0.6276, 0.7357, 0.0381]])
tensor([[0.4049, 1.1461, 1.4382, 0.8134],
        [1.4602, 1.2551, 1.4715, 0.0762]])


¿Cuál es el truco aquí? ¿Cómo es que podemos multiplicar un tensor de 2x4 por un
tensor 1x4?

El broadcasting es una forma de realizar una operación entre tensores que tienen
similitudes en sus formas. En el ejemplo anterior,
el tensor de cuatro columnas, el de una fila, se multiplica por *ambas filas* del de dos filas,
tensor de cuatro columnas.

Esta es una operación importante en Deep Learning. El ejemplo común es
multiplicar un tensor de pesos de aprendizaje por un *lote* de tensores de entrada,
aplicando la operación a cada instancia en el lote por separado, y
devolviendo un tensor de forma idéntica, al igual que nuestro (2, 4) \* (1, 4)
ejemplo anterior devolvió un tensor de forma (2, 4).

Las reglas para el broadcasting son:

- Cada tensor debe tener al menos una dimensión - no hay tensores vacíos.

- Comparando los tamaños de las dimensiones de los dos tensores, *yendo del último al
   primero:*

   - Cada dimensión debe ser igual, *o*

   - Una de las dimensiones debe ser de tamaño 1, *o*

   - La dimensión no existe en uno de los tensores

Los tensores de forma idéntica, por supuesto, son trivialmente "bradcasteables", como
viste antes.

Aquí hay algunos ejemplos de situaciones que respetan las reglas anteriores y
permiten el bradcasting:



In [ ]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3ra & 2da dims identicas a las de a, dim 1 ausente
print(b)

c = a * torch.rand(   3, 1) # 3ra dim = 1, 2da dim identica a la de a
print(c)

d = a * torch.rand(   1, 2) # 3ra dim identica a la de a, 2da dim = 1
print(d)

Para obtener más información sobre el broadcasting, consulte la documentación de PyTorch
 <https://pytorch.org/docs/stable/notes/broadcasting.html>`




### Más matemáticas con tensores

Los tensores PyTorch tienen más de trescientas operaciones que se pueden realizar
en ellos.

Aquí hay una pequeña muestra de algunas de las principales categorías de operaciones:




In [ ]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.svd(m3))       # singular value decomposition

Esta es una pequeña muestra de operaciones. Para más detalles y el inventario completo de
funciones matemáticas, echa un vistazo a la
`documentación` <https://pytorch.org/docs/stable/torch.html#math-operations>`__.



### Alteración de tensores en su lugar


La mayoría de las operaciones binarias entre tensores devolverán un tercer tensor nuevo. Cuando
decimos ``c = a * b`` (donde ``a`` y ``b`` son tensores), el nuevo tensor
``c`` ocupará una región de memoria distinta de los otros tensores.

Sin embargo, hay ocasiones en las que es posible que desee alterar un tensor en su lugar:
por ejemplo, si está haciendo un cálculo por elementos en el que puede
descartar valores intermedios. Para esto, la mayoría de las funciones matemáticas tienen un
versión con un guión bajo adjunto (``_``) que alterará un tensor en su
lugar.

Por ejemplo:




In [ ]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # esta operación crea un nuevo tensor en la memoria
print(a)              # a no ha cambiado 

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note el guión bajo
print(b)              # b ha cambiado

Para las operaciones aritméticas, existen funciones que se comportan de manera similar:



In [ ]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Tenga en cuenta que estas funciones aritméticas in situ son métodos del objeto ``torch.Tensor``, no adjunto al módulo ``torch`` como muchos
otras funciones (por ejemplo, ``torch.sin()``). Como puedes ver desde
``a.add_(b)``, *el tensor de llamada es el que se cambia en
lugar.*

Existe otra opción para colocar el resultado de un cálculo en un
tensor asignado existente. Muchos de los métodos y funciones que hemos visto
hasta ahora, ¡incluidos los métodos constructores! , tienen un argumento ``out`` que
le permite especificar un tensor para recibir la salida. Si el tensor ``out``
es de la forma correcta y ``dtype`` correcto, esto puede suceder sin una nueva asignación de memoria:




In [ ]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # el contenido de c ha cambiado

assert c is d           # se fija si c & d son el mismo objeto, no que solo contienen los mismos valore
assert id(c), old_id    # se asegura que el nuevo c sea el mismo que el viejo

torch.rand(2, 2, out=c) # funciona también para constructores
print(c)                # c ha cambiado nuevamente
assert id(c), old_id    # todavía es el mismo objeto

Copiando tensores
---------------

Como con cualquier objeto en Python, asignar un tensor a una variable convierte a la variable en una *etiqueta* del tensor y no la copia. Por ejemplo:




In [4]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # al cambiar a
print(b)       # ...b también se altera

tensor([[  1., 561.],
        [  1.,   1.]])


Pero, ¿qué sucede si deseas una copia separada de los datos para trabajar? El método ``clone()`` está ahí para ti:




In [ ]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

Manipulación de la forma del tensor
--------------------------

A veces, necesitarás cambiar la forma de tu tensor. A continuación, veremos algunos casos comunes y cómo manejarlos.

###Cambiar el número de dimensiones


Un caso en el que podría necesitar cambiar la cantidad de dimensiones es pasar una sola instancia como entrada a su modelo. Los modelos de PyTorch generalmente esperan *lotes* de entrada.

Por ejemplo, imagine tener un modelo que funcione con imágenes de 3 x 226 x 226, un cuadrado de 226 píxeles con 3 canales de color. Cuando lo cargues y lo transformes, obtendrás un tensor de forma ``(3, 226, 226)``. Sin embargo, su modelo espera una entrada de forma ``(N, 3, 226, 226)``, donde ``N`` es el número de imágenes en el lote. Entonces, ¿cómo se hace un lote de uno?




In [ ]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

El método ``unsqueeze()`` agrega una dimensión de extensión 1.
``unsqueeze(0)`` lo agrega como una nueva dimensión cero - ¡ahora tienes un lote de uno!

Estamos aprovechando el hecho de que cualquier dimensión de extensión 1 *no* cambia el número de elementos en el tensor.




In [ ]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

Continuando con el ejemplo anterior, digamos que la salida del modelo es un vector de 20 elementos para cada entrada. Entonces esperaría que la salida tuviera la forma ``(N, 20)``, donde ``N`` es el número de instancias en el lote de entrada. Eso significa que para nuestro lote de entrada única, obtendremos una salida de forma ``(1, 20)``.

¿Qué sucede si desea realizar un cálculo *no por lotes* con esa salida, algo que solo espera un vector de 20 elementos?




In [5]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.5052, 0.4619, 0.9835, 0.5341, 0.5414, 0.7336, 0.8064, 0.4359, 0.1039,
         0.7360, 0.5491, 0.8013, 0.2305, 0.6235, 0.4822, 0.3123, 0.0474, 0.1107,
         0.5544, 0.5571]])
torch.Size([20])
tensor([0.5052, 0.4619, 0.9835, 0.5341, 0.5414, 0.7336, 0.8064, 0.4359, 0.1039,
        0.7360, 0.5491, 0.8013, 0.2305, 0.6235, 0.4822, 0.3123, 0.0474, 0.1107,
        0.5544, 0.5571])
torch.Size([2, 2])
torch.Size([2, 2])


Puede ver en las formas que nuestro tensor bidimensional ahora es
1-dimensional, y si miras de cerca la salida de la celda de arriba
verás que imprimir ``a`` muestra un conjunto "extra" de corchetes
``[]`` debido a que tiene una dimensión adicional.

Solo puede hacer ``squeeze()`` sobre las dimensiones de tamaño 1. Vea arriba, donde tratamos de comprimir una dimensión de tamaño 2 en ``c``, y terminamos recuperando la misma forma con la que comenzamos. Las llamadas a ``squeeze()`` y ``unsqueeze()`` solo pueden actuar en dimensiones de tamaño 1 porque, de lo contrario, cambiaría el número de elementos en el tensor.

Otro lugar en el que podrías usar ``unsqueeze()`` es para facilitar el broadcasting. Recuerde el ejemplo anterior donde teníamos el siguiente código:

In [6]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

tensor([[[0.7708, 0.7708],
         [0.7431, 0.7431],
         [0.0831, 0.0831]],

        [[0.7708, 0.7708],
         [0.7431, 0.7431],
         [0.0831, 0.0831]],

        [[0.7708, 0.7708],
         [0.7431, 0.7431],
         [0.0831, 0.0831]],

        [[0.7708, 0.7708],
         [0.7431, 0.7431],
         [0.0831, 0.0831]]])


El efecto neto de eso fue operar con broadcast sobre las dimensiones 0 y 2, lo que provocó que el tensor aleatorio de 3 x 1 se multiplicara elemento a elemento por cada columna de 3 elementos en ``a``.

¿Qué pasaría si el vector aleatorio hubiera sido un vector de 3 elementos? Perderíamos la capacidad de hacer broadcasting, porque las dimensiones finales no coincidirían de acuerdo con las reglas del broadcasting. ``unsqueeze()`` viene al rescate:




In [ ]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # intentar multiplicar a * b dará un error de tiempo de ejecución
c = b.unsqueeze(1)       # cambiar a un tensor bidimensional, agregando un nuevo dim al final
print(c.shape)
print(a * c)             # ¡El broadcast funciona de nuevo!

Los métodos squeeze() y unsqueeze() también tienen versiones in situ, squeeze_() y unsqueeze_():




In [10]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


A veces querrá cambiar la forma de un tensor de forma más radical, conservando al mismo tiempo la cantidad de elementos y su contenido. 

``reshape()`` hará esto por ti, siempre que las dimensiones que solicites produzcan el mismo número de elementos que tiene el tensor de entrada:




In [11]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


El argumento ``(6 * 20 * 20,)`` en la línea final de la celda anterior se debe a que PyTorch espera una **tupla** al especificar una forma de tensor, pero cuando la forma es el primer argumento de un método, nos permite hacer trampa y simplemente usar una serie de números enteros. Aquí, tuvimos que agregar los paréntesis y la coma para convencer al método de que se trata realmente de una tupla de un elemento.

Cuando pueda, ``reshape()`` devolverá una *vista* del tensor a ser
cambiado, es decir, un objeto tensor separado que mira la misma región subyacente de la memoria. *Esto es importante:* Eso significa que cualquier cambio realizado en el tensor fuente se reflejará en la vista de ese tensor, a menos que le hagas ``clone()``.

Para obtener más información, consulte la
documentación <https://pytorch.org/docs/stable/torch.html#torch.reshape>




Puente con NumPy
------------

En la sección anterior sobre broadcasting, se mencionó que la semántica de broadcasting de PyTorch es compatible con la de NumPy, pero la afinidad entre PyTorch y NumPy es aún más profunda que eso.

Si tiene código científico o de ML pre-existente con datos almacenados en NumPy ndarrays, es posible que desee expresar esos mismos datos como tensores PyTorch, ya sea para aprovechar la aceleración GPU de PyTorch o sus abstracciones eficientes para construir modelos neuronales. 

Pues es fácil cambiar entre ndarrays y tensores PyTorch:




In [12]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


PyTorch crea un tensor de la misma forma y que contiene los mismos datos que los arreglos NumPy, llegando incluso a mantener el tipo de datos flotante de 64 bits predeterminado de NumPy.

La conversión puede ir fácilmente a la inversa:




In [13]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.2461, 0.4066, 0.0241],
        [0.2464, 0.3896, 0.7089]])
[[0.24610507 0.40662938 0.02413321]
 [0.24637604 0.3895728  0.7088829 ]]


Es importante saber que estos objetos convertidos utilizan *la misma memoria subyacente* que sus objetos de origen, lo que significa que los cambios en uno se reflejan en el otro:




In [14]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.24610507  0.40662938  0.02413321]
 [ 0.24637604 17.          0.7088829 ]]
